Initial calendar view setting
davish/obsidian-full-calendar pull request #149
Opened 2022-08-29 00:56 UTC by MatteoGalletta

Allows to set the default view in the plugin settings.
This currently works only for desktop, I don't really know how to implement the mobile version, since the check gets done on the screen dimensions. The first and immediate solution I can think of consists of adding two different rows in the settings (one for mobile, one for desktop), but maybe it could result overwhelming.

Fixes #124

2022-10-05 18:33 UTC, davish commented
Personally, I think that two different rows in Settings makes sense, since folks often want to see different views depending on the device they're on.

2022-10-15 16:33 UTC, MatteoGalletta commented
Thanks for the feedback, I added the mobile option too.

2022-10-29 16:14 UTC, davish requested changes
Code looks great! One change to make sure the default view doesn't change from Week to Day for everyone on desktop.

2022-10-29 16:14 UTC, davish commented on src/settings.ts
> +		desktop: "timeGridDay",
The default desktop view should remain `timeGridWeek` to match the behavior before this PR.

2022-11-06 21:30 UTC, MatteoGalletta commented on src/settings.ts
> +		desktop: "timeGridDay",
Completely agree.

2022-11-09 00:36 UTC, davish requested changes
Sorry for one last request -- I didn't catch this the first time! Thanks again for your work here.

2022-11-09 02:01 UTC, davish approved these changes

2022-11-09 02:03 UTC, merged