Always open in new tab setting
davish/obsidian-full-calendar pull request #497
Opened 2023-09-10 09:19 UTC by marienvo

I prefer the calendar tab not to close when opening an event (but open a new tab instead). This way its easier to compare and switch notes of multiple events. So maybe we could add this setting to always have clicks to open in a new tab?

**Without setting** (current, many clicks needed)
![current](https://github.com/davish/obsidian-full-calendar/assets/8506573/68d18f20-3e43-46f6-8374-60a620015e81)

**With setting** (this PR, less clicks needed)
![new](https://github.com/davish/obsidian-full-calendar/assets/8506573/187713e6-7eb3-4f21-b01d-90f2c4fcd342)

**Invert Ctrl-setting for opening modal vs file**
Also (second commit in this PR), I tend to want to open the note more than I want to open the edit modal. So I added a setting for inverting the modifier key as well (ctrl for opening modal instead of ctrl for opening the file - notes are central for me):

![Screenshot from 2023-09-10 11-06-21](https://github.com/davish/obsidian-full-calendar/assets/8506573/bfc86994-62eb-43e0-9109-e23782ea7b20)

2023-10-02 02:50 UTC, davish requested changes
Thank you for your contribution! Just a few suggestions before merging.

2023-10-02 02:50 UTC, davish commented on src/ui/settings.ts
> +    alwaysOpenInNewTab: boolean;
```suggestion
    alwaysOpenInNewTab?: boolean;
```

Both of these settings should be optional, since they won't be present in existing Full Calendar installations. Following the type errors should lead you to add some more edge cases to fill in the defaults as they should in those cases.

2023-10-02 02:50 UTC, davish commented on src/ui/actions.ts
> +    settings?: FullCalendarSettings
```suggestion
    openInNewTab: boolean
```
Could you pass the setting in as its own parameters rather than passing in the whole settings object? I'd prefer it to be explicit what settings `openFileForEvent` is using from its type signature.

2023-10-28 16:02 UTC, marienvo commented on src/ui/actions.ts
> +    settings?: FullCalendarSettings
Sure, just updated the branch

2026-03-07 11:34 UTC, closed without merging