Add minimal CalDAV support
davish/obsidian-full-calendar pull request #62
Opened 2022-03-14 16:46 UTC by dojoteef

I've added minimal support for querying events from a CalDAV server. This allows for people to use private Apple Calendars, rather than resorting to making those calendars public. It's currently a very dumb and simple implementation — it just queries *all* events from the calendar. This can be optimized to only query events for certain days (depending on the calendar view), but I don't think the code is currently setup for this type of querying and it seemed like a larger change to add.

Additionally, having full CalDAV support would make two-way sync (#25) possible. I couldn't find a minimal CalDAV javascript library that also allows overriding `fetch`. I initially tried using [tsdav](https://tsdav.vercel.app), which is a typescript library for WebDAV/CalDAV/CardDAV, but I ran into CORS issues, which is why I wrote my own minimal xml query to the CalDAV server using Obsidian's `request` API method.

2022-03-14 20:48 UTC, dojoteef commented
Accidentally deleted the branch while I was trying to test it on mobile. Doh!

2022-03-14 23:33 UTC, davish commented
Thanks so much for the contribution @dojoteef! This is an awesome addition. I will submit a full review of your PR shortly, but could you run `npm run fix` to run prettier on this branch? Thank you!

2022-03-15 00:00 UTC, davish requested changes
Have some comments / questions, but generally looks great! Thanks again for submitting and looking forward to getting this merged in :)

2022-03-15 00:00 UTC, davish commented on src/view.ts
> +							body: `<c:calendar-query xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
You mentioned in the PR description that you were worried about downloading the whole calendar. Personally, I think that this method is the right way to go. Getting the whole calendar ahead-of-time means that you won't get latency every time you hit "next week" or "previous week".

Could you link me to some documentation on CalDAV? And maybe put a link in the comments here, since this query seems kind of involved.

2022-03-15 01:58 UTC, dojoteef commented on docs/sync/caldav.md
> +Add any calendar over CalDAV. This is currently for [private Apple Calendars](https://support.apple.com/guide/icloud/share-a-calendar-mm6b1a9479/icloud), but could support [private Google Calendars](
Will do!

2022-03-15 02:14 UTC, dojoteef commented on src/view.ts
> +							ontext(text) { if (calData) expanders = expanders.concat(makeICalExpander(text)); }
The way CalDAV works, each `VEVENT` that's returned is wrapped in its own `VCALENDAR`. That's why we need an expander for each event. [ical.js](https://github.com/mozilla-comm/ical.js/wiki#icalendar-data) handles this just fine, but the [code for IcalExpander](https://github.com/davish/obsidian-full-calendar/blob/12b7ca2b0c7c806e46c7abd86742ed2794471035/vendor/fullcalendar-ical/ical-expander/IcalExpander.js#L15-L16) assumes it's just a single `VCALENDAR`, which is why I decided to have an array of `IcalExpander`s.

2022-03-15 02:25 UTC, dojoteef commented on src/view.ts
> +							body: `<c:calendar-query xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
I used a combination of info from [sabre/dav](https://sabre.io/dav/building-a-caldav-client/) and the [CalDAV RFC](https://datatracker.ietf.org/doc/html/rfc4791).

I agree that it would be good to download the whole calendar at once, but that's a very slow operation to do each time you load the calendar. The sabre/dav doc I linked specifically states:
> Every single event and task is encoded as an iCalendar object. I strongly recommend _always_ retaining the iCalendar the server sent to you.

I think if you did store the calendar data, it would more easily allow for two-way sync in the future and make updating super fast. Then you'd only have to check if the calendar hash (`ctag`) has changed, then query any changed events (using `etag`s). That means you only spend the fixed cost of downloading the entire calendar once and then make updates by querying the small amount of changes that might have occurred in the meantime.

If you do end up storing the calendar data, it might make sense to encode it in the YAML frontmatter of an event markdown document. That could become the basis of the two-way sync.

2022-03-15 02:27 UTC, dojoteef commented
> Thanks so much for the contribution @dojoteef! This is an awesome addition. I will submit a full review of your PR shortly, but could you run `npm run fix` to run prettier on this branch? Thank you!

I actually did run `npm run fix` before submitting. It doesn't seem to fix the tabs vs spaces issues in the `.ts` files for some reason, so I've been doing that manually (sorry my environment is set to always convert tabs to spaces and isn't super easy to change currently).

2022-03-15 02:42 UTC, davish commented on src/view.ts
> +							body: `<c:calendar-query xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
Oof. Yeah, that does sound like it's super heavyweight. I'll take a look through the documents you linked, hopefully there's an explanation for why the protocol was formatted like that.

I was planning on implementing a stale-while-revalidating cache strategy at first, but checking the checksum / ctag is a great idea!

2022-03-15 02:44 UTC, davish commented
> > Thanks so much for the contribution @dojoteef! This is an awesome addition. I will submit a full review of your PR shortly, but could you run `npm run fix` to run prettier on this branch? Thank you!
> 
> I actually did run `npm run fix` before submitting. It doesn't seem to fix the tabs vs spaces issues in the `.ts` files for some reason, so I've been doing that manually (sorry my environment is set to always convert tabs to spaces and isn't super easy to change currently).

Oh gosh, is this whole project formatted with tabs instead of spaces? I'm firmly in the spaces camp, but VSCode must have detected tabs from the sample plugin template and ran with it. I'll try and move over to spaces at some point.

2022-03-15 02:55 UTC, davish approved these changes

2022-03-15 02:57 UTC, dojoteef commented
There are two current issues I've run into:
* for some reason my request isn't working on mobile
* now that i made the changes from `textarea` to `input` for username and password, the `textarea` for the url is completely squashed on mobile

2022-03-15 02:59 UTC, davish commented
> There are two current issues I've run into:
> 
> * for some reason my request isn't working on mobile
> * now that i made the changes from `textarea` to `input` for username and password, the `textarea` for the url is completely squashed on mobile

Hmm. I'm not sure the best way to debug the mobile issue. For the `input`s, make sure their style object still has a `maxWidth` property. Alternatively, you can set a `minWidth` percentage on the URL `textarea`.

2022-03-15 03:02 UTC, davish commented
Also thanks for sending me those links for CalDAV! This seems like an awesome protocol, and most likely the way to go for supporting two-way calendar sync, rather than interfacing directly with the Google OAuth API, since that would have to be replicated for every cloud provider.

Please let me know if this is something you might be interested in working on in the future -- it would be awesome to have your help on this feature!

2022-03-24 21:57 UTC, dojoteef commented
Sorry I've been MIA for a little while. I've been a bit busy and I've also been struggling to understand why my approach doesn't work on mobile. My only guess is that Apple is specifically blocking requests to the caldav.icloud.com domain if an app has not requested permissions to access the user's calendar.

In pursuit of fixing the issue, I came across the [dav package](https://www.npmjs.com/package/@types/dav) and it allows for overriding the transport, such that I can use Obsidian's `request` and `requestUrl` methods, rather than assuming the use of XMLHttpRequest like [tsdav](https://tsdav.vercel.app/) does.

I have a branch called [caldav_minimal_mobile](https://github.com/dojoteef/obsidian-full-calendar/tree/caldav_minimal_mobile) where I've been trying to work through the issues on mobile. I've integrated the `dav` package there, and it makes querying calendars much easier. Now you can simply use https://caldav.icloud.com with your username and application specific password to access all your calendars.

I'll probably make an attempt to try CalDAV using Google's API over OAuth. It's kind of a pain for users to setup (since they have to technically register as a Google developer to get API access), but it should allow me to test my assumption that iOS is actually blocking the request to the iCloud servers. Either that, or I'll look at a way to proxy all the https://caldav.icloud.com requests to ensure the problem is indeed due to permissions.

If it turns out to be a permissions issue, then I doubt there's anything that can be done (other than to potentially ask Obsidian to request permissions). Since they haven't exposed notifications on iOS, I'm not sure how responsive they are to the notion of asking for permissions that are only used by plugins.

If I'm successful, I might just scrapped this pull request and make a new one (since some of the guts will have changed considerably).

2022-03-25 03:36 UTC, dojoteef commented
Actually, I just made some progress (it's really slow going for me since I'm not super familiar with web dev and there isn't an easy way to debug on iOS). It turns out that you cannot use `Buffer` to base64 encode strings in the iOS Obsidian app, so I had to change it to use `window.btoa`.

I can now successfully make queries on mobile, but it seems to indicate there are no calendars. It doesn't error anywhere that I can see, but the output indicates there are no calendars (though the same code succeeds just fine on desktop — story of my life). I'll have to add more debug logging. Just wanted to give a quick update to indicate it's not a permissions issue on mobile.

I'll try to make some more progress in the next couple days. I think if we get the [dav package](https://github.com/lambdabaa/dav/) integrated, it should be pretty straightforward to begin supporting two-way syncing.

2022-03-25 21:35 UTC, dojoteef commented
@davish I finally got it working on desktop and mobile! There were a number of little niggling issues, e.g. an implicit integer to string conversion that worked fine on desktop, but failed on mobile.

That said, I think this probably still needs to be iterated on before getting merged. The main change that I think would be beneficial is to make a new flow for adding a CalDAV source. When you select the "Remote Calendar (CalDAV)" option, I envision that opening a new dialog that walks you through the configuration. That way allows a few quality of life improvements:

1. The plugin can have specialized flows for common CalDAV implementations. For example, if you choose to sync with Apple's CalDAV server, users won't have to manually set the URL to `https://caldav.icloud.com`.
2. It'll make it much easier to fit the input elements on mobile since they could each be laid out in a separate row, rather than all bunched up together in a single row.
3. It would allow more complicated flows where people can select which calendars they want to import from the CalDAV server and color each calendar separately. With the switch to using the `dav` package my code now loads all the calendars the user has and they are all colored the same (previously users had to manually figure out the urls for each calendar, but that now happens through automatic discovery in the `dav` package).

Do you think I should get the current changes merged in (after you review and approve them) then work on these improvements, or would you prefer the improvements get put in as part of this pull request?

2022-03-27 19:27 UTC, davish commented
Hi @dojoteef, thanks so much for the continued work on this feature! I'm actually in the middle of a pretty considerable refactor of the code that will make future development easier. It probably makes sense to wait to merge this code at least until it can get rebased on top of the refactored code.

 I don't anticipate that it will be a ton of work on your side. The main difference is that `CalendarSource`s are now represented by a class, with methods on the class to get the FullCalendar-compatible objects to pass into the calendar. It's just better way to organize the code that's currently in `view.ts`. 

I'll post those changes as a PR and link to them here. Everything compiles properly, but I'm still chasing down a few lingering bugs, so hopefully it can get merged in soon.

You mentioned that you wanted to iterate on the code a bit more. Feel free to do that in this PR and re-request my review when you would like my feedback! Let me know if you've got any questions on any of this.

Cheers!

2022-03-27 19:33 UTC, davish commented
I posted my WIP in #76 if you're interested in taking a look / rebasing off of it!

2022-03-29 16:46 UTC, dojoteef commented
Alright, I've created a new add calendar flow that works much nicer on desktop and mobile. I've also merged the changes from #76 into my current code. You can try out the changes by using [BRAT](https://github.com/TfTHacker/obsidian42-brat) on my repo `dojoteef/obsidian-full-calendar`.

2022-03-30 14:59 UTC, dojoteef commented
Okay, I've finally gotten things to a point that I think I'm comfortable merging once #76 is merged. The only thing that probably needs updating are some of the gifs that show how to add a Google Calendar. I've already updated my gif for the CalDAV sync using the new flow. That should help you see what the new Add Calendar flow looks like.

Basically, I open a modal that allows you to add (or import) calendars. For CalDAV/iCloud, the flow is to import calendars from CalDAV (including pulling the calendar colors automatically). You then get to see the list of added calendars and will need to explicitly save them, like you currently do. You can only modify the colors or delete a calendar from the list of calendars. To add a calendar you have to use the modal flow. This approach is the only one that makes sense with CalDAV since there are potentially multiple calendars that need to be imported.

There are a number of follow-up steps that make sense once this is merged in:
* There needs to be some way to persist the CalDAV calendar data between opening and closing Obsidian. Querying for the full calendar data each time we open Obsidian is just very slow for any reasonably sized calendar. It also doesn't allow for two-way sync.
* It would be good to change the event frontmatter fields to ones that better mirror what ICS/CalDAV use. That would make interoperability much easier. For example, there is currently a difference between date and time in the frontmatter, but that could just be a single field (also mentioned in #70).
* It would be great to have a single standard interface for reading/writing events. I understand that's what you're trying to do with #76, but I wonder if it can be stream-lined even more.
* TBH, I would just drop support for the current `gcal` source. It's extra maintenance without providing any improvement over the ICS source.
* In order to support [OAuth for Google CalDAV,](https://developers.google.com/identity/protocols/oauth2/native-app) you need to make a Google API account and register this plugin as an application on Google API console. It actually looks [quite involved to support](https://developers.google.com/identity/protocols/oauth2/native-app), especially since on mobile you [cannot initiate the flow in a a webview](https://developers.googleblog.com/2021/06/upcoming-security-changes-to-googles-oauth-2.0-authorization-endpoint.html), which is what [CapacitorJS](https://capacitorjs.com) uses on [iOS](https://capacitorjs.com/docs/ios) and [Android](https://capacitorjs.com/docs/android) (the Obsidian mobile apps are developed using CapacitorJS).

2022-03-30 19:31 UTC, davish commented
Sounds great, @dojoteef! I'm planning on wrapping up #76 tonight (EDT) and getting it merged in, so I can focus on your PR after that. I'll also write up some thoughts on the follow-up steps you mentioned but the tl;dr is that I'm generally in agreement with you 😃

2022-03-31 00:38 UTC, davish commented
Sorry about that! GitHub closed the PR automatically because I'd set the diff to the `refactor/models` branch I'd just merged in.

2022-03-31 00:39 UTC, davish commented
I just merged in #76 by squashing the commits in the PR -- @dojoteef you'll likely have to rebase your changes. Let me know if you need help with the rebase!

2022-03-31 00:59 UTC, davish commented
Hey @dojoteef, now that #76 is merged in, getting in this PR is my next priority. I'll have a code review for you tonight, and will hopefully also have some UI/UX feedback on the new modal. 

I'm really sorry about the rebase hell I've created by choosing the "squash + merge" PR option on the last PR. I'd used it on other personal projects before but I didn't realize how it could completely mess up in-progress PRs. Please let me know if you want me to take a try at resolving it, since I did cause that issue in the first place. I'll make sure to just merge in PRs with a merge commit next time.

I wanted to take some time to address the points you brought up in your last comment:

> There needs to be some way to persist the CalDAV calendar data between opening and closing Obsidian. Querying for the full calendar data each time we open Obsidian is just very slow for any reasonably sized calendar. It also doesn't allow for two-way sync.

I agree -- I was trying to do this earlier, but didn't know if there was an "accepted" way for plugins to persist non-settings information like a cache. My concern is having the entire cache synced through obsidian-git or the official sync plugin. I just opened an issue to track this (#77)
     
> It would be good to change the event frontmatter fields to ones that better mirror what ICS/CalDAV use. That would make interoperability much easier. For example, there is currently a difference between date and time in the frontmatter, but that could just be a single field (also mentioned in https://github.com/davish/obsidian-full-calendar/issues/70).

I also agree here. The distinct fields are left over from early in development when you had to edit frontmatter directly to create/edit events. I'll prioritize #70 and most likely default to the format that just has `start` and `end` datetimes, since  that also matches the FullCalendar library.

> It would be great to have a single standard interface for reading/writing events. I understand that's what you're trying to do with https://github.com/davish/obsidian-full-calendar/pull/76, but I wonder if it can be stream-lined even more.

This is definitely a work-in-progress, #76 was my attempt to clean up a ball of spaghetti code in anticipation for #28 adding a whole new way to store events within local files. But the API can certainly be improved, and I'd also love any feedback you have on how to go forward.

> TBH, I would just drop support for the current gcal source. It's extra maintenance without providing any improvement over the ICS source.

I was thinking this too. There's a `[deprecated]` notice in the docs, but I filed an issue to remove it (#78) and I'll do so soon.

> In order to support [OAuth for Google CalDAV,](https://developers.google.com/identity/protocols/oauth2/native-app) you need to make a Google API account and register this plugin as an application on Google API console. It actually looks [quite involved to support](https://developers.google.com/identity/protocols/oauth2/native-app), especially since on mobile you [cannot initiate the flow in a a webview](https://developers.googleblog.com/2021/06/upcoming-security-changes-to-googles-oauth-2.0-authorization-endpoint.html), which is what [CapacitorJS](https://capacitorjs.com/) uses on [iOS](https://capacitorjs.com/docs/ios) and [Android](https://capacitorjs.com/docs/android) (the Obsidian mobile apps are developed using CapacitorJS).

I've already created an OAuth app for the plugin, but haven't gotten around to starting to play with the OAuth flow. That's really unfortunate about mobile. I wonder if we can extend the `obsidian://` URI to allow OAuth to authenticate in the native browser and redirect back to the app with the right credentials.

2022-03-31 01:43 UTC, dojoteef commented
> I agree -- I was trying to do this earlier, but didn't know if there was an "accepted" way for plugins to persist non-settings information like a cache. My concern is having the entire cache synced through obsidian-git or the official sync plugin. I just opened an issue to track this (#77)

I'll share my thoughts directly on that issue.

> I also agree here. The distinct fields are left over from early in development when you had to edit frontmatter directly to create/edit events. I'll prioritize #70 and most likely default to the format that just has `start` and `end` datetimes, since that also matches the FullCalendar library.

I'll also share my thoughts directly on that issue.

> This is definitely a work-in-progress, #76 was my attempt to clean up a ball of spaghetti code in anticipation for #28 adding a whole new way to store events within local files. But the API can certainly be improved, and I'd also love any feedback you have on how to go forward.

I get it and I appreciate that fact. I guess my concern is that right now there are explicit checks for the type of event, does it come from a note, ics, caldav, etc. It would be good to abstract that away behind a single interface that allows for reading fields, updating them, and persisting them. If an operation isn't supported, an error can be thrown that can be handled appropriately (either eat it or raise it to the user if needed). The idea being that only the event code itself cares about the underlying source, not any external code.

> I've already created an OAuth app for the plugin, but haven't gotten around to starting to play with the OAuth flow. That's really unfortunate about mobile. I wonder if we can extend the `obsidian://` URI to allow OAuth to authenticate in the native browser and redirect back to the app with the right credentials.

I'm not sure how easy it is to use the `obsidian://` URI, but we can certainly try. In order to support OAuth for CalDAV, we probably need to write our own OAuth transport adapter [like the one from the dav package](https://github.com/lambdabaa/dav/blob/master/lib/transport.js#L68). That's what I had to do to support basic auth, since the dav package used `XMLHttpRequest`s which result in CORS errors. The adapter I wrote instead uses the Obsidian API's `request` function. I initially as planning to see if I could write the code and test it for Google calendars, but since I don't use Google calendar it feels like a big hassle that I'm not super keen to deal with 😕, especially once I saw the difficulty of supporting mobile (or at least it seems difficult).

2022-03-31 01:43 UTC, davish requested changes
Thanks so much for the work here again! I also looked at the new UI elements and those look great, no comments from the UX side that aren't mentioned in the comments on the code.

Most of the changes are pretty small, nothing should require any huge changes to your approach.

2022-03-31 01:43 UTC, davish commented on docs/sync/caldav.md
> +# Add remote calendar from CalDAV or iCloud
I think it might be worth just labeling this as the iCloud sync method for now, since it's the only one that's verified to work. You can leave a note at the bottom of the docs that this *should* accept any CalDAV username/password.

2022-03-31 01:43 UTC, davish commented on src/components/AddCalendarSource.tsx
> +function Directory<T extends Partial<CalendarSource>>({
Maybe naming this `DirectorySelect` would be a bit more specific?

2022-03-31 01:43 UTC, davish commented on src/components/AddCalendarSource.tsx
> +function Color<T extends Partial<CalendarSource>>({
Again a bit of a naming nitpick, but calling this `ColorPicker` would be more specific.

2022-03-31 01:43 UTC, davish commented on src/components/AddCalendarSource.tsx
> +	if (source.type === "caldav" || source.type === "icloud") {
A comment here about why these sources shouldn't have a colorpicker would be helpful.

2022-03-31 01:43 UTC, davish commented on src/components/AddCalendarSource.tsx
> +function Url<T extends Partial<CalendarSource>>({
```suggestion
function UrlInput<T extends Partial<CalendarSource>>({
```

2022-03-31 01:43 UTC, davish commented on src/components/AddCalendarSource.tsx
> +function Username<T extends Partial<CalendarSource>>({
```suggestion
function UsernameInput<T extends Partial<CalendarSource>>({
```

2022-03-31 01:43 UTC, davish commented on src/components/AddCalendarSource.tsx
> +	if (source.type === "local" || source.type === "icloud") {
Having these checks inside the components themselves makes managing the look of the form much more difficult since you have to go hunting through each individual component. Would it be possible to move these conditional checks into the main form component?

2022-03-31 01:43 UTC, davish commented on src/components/AddCalendarSource.tsx
> +function Password<T extends Partial<CalendarSource>>({
```suggestion
function PasswordInput<T extends Partial<CalendarSource>>({
```

2022-03-31 01:43 UTC, davish commented on src/components/AddCalendarSource.tsx
> +		await submit(setting as CalendarSource);
Before casting, it would be helpful to validate that every field is present, to prevent null/undefined errors outside of the view code.

2022-03-31 01:43 UTC, davish commented on src/components/CalendarSetting.tsx
> +	if (source.type !== "local") {
Ditto on this file for moving the checks into the main form. I know it makes the top-level component more difficult, but it makes the branching much more explicit.

2022-03-31 01:43 UTC, davish commented on src/components/CalendarSetting.tsx
> +function Directory<T extends Partial<CalendarSource>>({
Also ditto on naming these components along the lines of `DirectoryInput` rather than just `Directory` so it's clear what they are when they are used.

2022-03-31 01:43 UTC, davish commented on src/components/CalendarSetting.tsx
> +				disabled
Ah, I guess the idea is that users should remove the calendar and add a new one if they want to change the folder? That makes a lot more sense than what is there currently, so no need to change it for this PR.

With #28, however, I'd imagine there would be a lot more settings for the calendar surrounding where to store new events and under which heading. Do you think it would be easy to add a button to open an edit modal from the CalendarSettingRow in the future?

2022-03-31 01:43 UTC, davish commented on src/models/EventSource.ts
> +						return {
Surprised it works to just return an object from a `flatMap` lambda, I thought it only accepted arrays as the return value. `map` might be sufficient here.

2022-03-31 01:43 UTC, davish commented on src/settings.ts
> +				gcal: "Google (Readonly)",
Feel free to remove this option in this PR. I'll remove the plumbing for the `gcal` type in a later commit.

2022-03-31 01:43 UTC, davish commented on src/transport.ts
> +import { co } from 'co';
I'm very glad this didn't require forking a package :)

2022-03-31 01:43 UTC, davish commented on src/types.ts
> +export function partialCalendarSource(
```suggestion
export function makeDefaultPartialCalendarSource(
```

Maybe this name is too long but feel like it'll help just to be clear that this is adding _default_ values.

2022-03-31 01:43 UTC, davish commented on src/models/EventSource.ts
> +export class RemoteSource extends EventSource {
CalDAVSource might be a better name? Since the `ICSSource` also represents remote calendars.

2022-03-31 01:50 UTC, dojoteef commented on docs/sync/caldav.md
> +# Add remote calendar from CalDAV or iCloud
Actually, I did verify it works on other CalDAV servers. Specifically, I tried it on [NextCloud's playground](https://try.nextcloud.com) (which I think uses [Baikal](https://sabre.io/baikal/) under the hood).

2022-03-31 01:53 UTC, dojoteef commented on src/components/AddCalendarSource.tsx
> +		await submit(setting as CalendarSource);
I thought that's what `e.preventDefault` does. What exactly did you have in mind?

2022-03-31 01:57 UTC, dojoteef commented on src/components/CalendarSetting.tsx
> +				disabled
Should that be a per calendar setting, or would those make more sense as global settings?

2022-03-31 01:59 UTC, dojoteef commented on src/models/EventSource.ts
> +	info: CalDAVSource | ICloudSource;
The thing is, they are effectively identical. The only difference is that you don't need to explicitly provide the URL for the iCloud caldav server. That's just baked in. Technically, you can import iCloud calendars using the CalDAV flow, you just need to manually specify `https://caldav.icloud.com` (I've verified this).

2022-03-31 02:02 UTC, dojoteef commented
Thanks for the quick turnaround for the code review. I'll try to address the issues you brought up and update the pull tomorrow.

2022-03-31 02:04 UTC, davish commented on src/components/AddCalendarSource.tsx
> +		await submit(setting as CalendarSource);
Since `setting` is stored as a `Partial` type, it's possible that it doesn't have all the fields required on the `CalendarSource` type. By validate, I just mean make sure that all the fields are actually present on `setting` before calling `submit()`. `e.preventDefault()` just makes sure that the submit button doesn't try to reload the page like it would in a normal browser.

2022-03-31 02:07 UTC, davish commented on src/components/CalendarSetting.tsx
> +				disabled
I would guess that someone might want to have a calendar with meeting notes where each event is a full note, and also have a calendar where notes are stored in daily notes. There might also be calendars where there are multiple events as bullet points that live outside of daily notes. So I think those multi-event note calendars (official name tbd) would have different per-calendar settings.

2022-03-31 02:07 UTC, davish commented on src/models/EventSource.ts
> +	info: CalDAVSource | ICloudSource;
Good point, this is fine to keep then.

2022-03-31 16:19 UTC, dojoteef commented on src/transport.ts
> +import { co } from 'co';
Yeah, I decided to use this package mainly because I could easily modify it to add my own transport (unlike [tsdav](https://www.npmjs.com/package/tsdav)).

2022-03-31 16:31 UTC, dojoteef commented on src/models/EventSource.ts
> +export class RemoteSource extends EventSource {
Hmm... I went with `RemoteSource` because `CalDAVSource` is already [defined in types.ts](https://github.com/dojoteef/obsidian-full-calendar/blob/caldav_minimal/src/types.ts#L136) and I am actively referencing it in this file. TBH, I'm not too keen on the current namings. Maybe it's best to rename the `CalendarSource` and the associated types to `CalendarSourceConfig` and simply add `Config` to the end of them? It's a bit more long winded, but they just defined what the sources are. The actual sources are now defined in EventSource.ts

2022-03-31 16:48 UTC, dojoteef commented on src/components/CalendarSetting.tsx
> +				disabled
It's certainly possible to make some configuration options changeable on the `CalendarSettingRow`. For example, I made it such that you can change color. Changing directories might also make sense.

It's also possible to make a new modal for editing calendars, but I don't think it can be the same modal as adding them. The main issue is that for CalDAV you're actually importing a number of calendars, not a single calendar. Some of the settings should then not be editable (like the actual calendar url).

2022-03-31 16:58 UTC, davish commented on src/components/CalendarSetting.tsx
> +				disabled
Makes sense!

2022-03-31 17:03 UTC, davish commented on src/models/EventSource.ts
> +export class RemoteSource extends EventSource {
Yeah, this is fine to keep for now, naming is one of the hard problems of computer science, and I can work on naming down the line.

2022-04-05 21:58 UTC, davish commented
Hi @dojoteef, unfortunately I've been pretty sick since Friday, but I'm starting to feel better, so hopefully I'll be able to take another look tomorrow!

2022-04-08 02:10 UTC, dojoteef commented
No worries. I hope you feel better soon!

2022-04-09 15:25 UTC, davish approved these changes
This looks great, @dojoteef! Thanks so much for the work here. I'll run CI checks and merge this in. I'll work on updating some more of the GIFs in the documentation this afternoon and hopefully will cut a release later today.

2022-04-09 15:25 UTC, davish commented on src/components/AddCalendarSource.tsx
> +		await submit(setting as CalendarSource);
Ah, that should do the trick!

2022-04-09 15:25 UTC, davish commented on src/components/AddCalendarSource.tsx
> +				{source.type === "local" ? (
This logic is much more clear! Thanks for making this change.

2022-04-09 15:25 UTC, davish commented on src/components/CalendarSetting.tsx
> +			{isCalDAV && <Username source={setting} />}
This should probably be `UsernameSetting` to keep it in line with the other components. Don't worry about changing this, I can handle it before cutting a release.

2022-04-09 15:25 UTC, davish commented on src/components/CalendarSetting.tsx
> +		this.state = { sources: props.sources, dirty: false };
This can still be a function component with the `useState` and `useEffect` hooks. I'll add that as a TODO for a future refactor.

2022-04-09 15:25 UTC, davish commented on src/settings.ts
> +import { createElement, useState } from "react";
I don't think `useState` is used in this file right now.

2022-04-09 15:28 UTC, merged