Cache CalDAV calendars
davish/obsidian-full-calendar pull request #96
Opened 2022-04-18 03:06 UTC by dojoteef

This pull request is kind of massive. Sorry about that! I implemented caching of CalDAV calendars as discussed in #77. This should also address the issue brought up in #88.

In the process of adding support for caching, I also ended up adding support for RRule based events. It's only implemented for CalDAV events, but it should be relatively straightforward to allow that for any events since there is support in the `EventFrontmatter`.

Also, this change fixed the the `prettier` scripts to properly format all the Typescript files, which means that some files only have a change in whitespace. This simply required adding some quotations marks around the glob pattern.

2022-04-18 03:14 UTC, dojoteef commented on src/models/CalDAVEvent.ts
> +		let icsData = await vault.adapter.read(path);
To support writing the cache files into a `.cache` directory I needed to use the `DataAdapter` interface in the `Vault` rather than the `AbstractFile` interface. This should help prevent cluttering up people's vaults as dot files are ignored.

2022-04-18 03:16 UTC, dojoteef commented
Note that I haven't put support for querying the CalDAV server for updates based on the `ctag` or `etag`, so after import the calendar is currently static. I'll have to add support for that before this PR gets merged.

2022-04-18 13:36 UTC, dojoteef commented
Just rebased with main. Will look to implement `ctag` and `etag` support soon. In the meantime, feel free to look over the current code. It shouldn't change too much to support refreshing from the server.

2022-04-21 23:37 UTC, davish commented
@dojoteef would it be possible to submit another PR with just the changes to `prettier`? That would make this PR a lot easier to review if we could get the whitespace changes in first.

2022-04-21 23:40 UTC, davish commented
Never mind, I was able to fix prettier and push to master. Thanks so much again for the PR -- I'll start taking a look and hopefully have a review for you in the next day or so!

2022-05-06 15:22 UTC, dojoteef commented
@davish Unfortunately, I've been a bit busy and so haven't had an opportunity to work on this more yet. If you have a chance to give any preliminary feedback on the review I'll try to incorporate your suggestions when I get a chance to add server updating based on `ctag` and `etag`.

2022-05-08 16:37 UTC, davish requested changes
Thanks so much for submitting this PR, @dojoteef! Really excited for another step towards useful, effective sync in the plugin. I have a decent number of comments here, so feel free to ask me questions about anything that I brought up.

One thing that I did want to reiterate at the top-level here is that I think the cache strategy that makes the most sense to use is stale-while-revalidate. There's an explanation of the cache strategy here: https://web.dev/stale-while-revalidate/#what's-it-mean. Here's some python-ish psuedocode with what I mean:

```python
def getCalendar(cal):
   if getCache(cal):
      if cache is valid:
          return cache.calendar
      else if cache is stale:
          async:  # asynchronously update the cache and then update the user's view.
             response = getCalendarFromRemote(cal)
             setCache(response)
             updateCalendar(response.calendar)
          return cache.calendar; # return the stale calendar to show something to the user immediately
   else if no cache found:
      response = getCalendarFromRemote(cal)
      setCache(response)
      return response.calendar
```

2022-05-08 16:37 UTC, davish commented on src/models/EventSource.ts
> +		if (calendarCache === null) {
See my comment on the readCache() function about fetching the calendar in the case the cache doesn't exist instead of returning `null`. Instead, it should fetch the calendar from the source and update the cache if the cache isn't valid locally.

2022-05-08 16:37 UTC, davish commented on src/models/EventSource.ts
> +		if (!this.vault.adapter.exists(calendarPath)) {
It looks like this won't fetch the calendar if the cache is empty locally. So this will fail if a user deletes the cache. Instead, I think it's fine for this function to take more time and re-download the calendar if the cache isn't found. I think this should aim to use the [stale-while-revalidate](https://web.dev/stale-while-revalidate/) cache strategy. So when a user opens the calendar, it will show the "stale" cache while updating the cache behind the scenes. I'll make sure to make a top-level comment about this.

2022-05-08 16:37 UTC, davish commented on src/settings.ts
> +				let modal = new ReactModal(app, async () => {
Prettier is not kind to this lambda, lol.

2022-05-08 16:37 UTC, davish commented on src/settings.ts
> +import { createElement } from "react";
This is a nitpick, but namespacing helper functions with `React` is helpful for readability. `createElement` doesn't look react-specific.
```suggestion
import * as React from "react";
```

2022-05-08 16:37 UTC, davish commented on src/settings.ts
> +					return createElement(AddCalendarSource, {
```suggestion
					return React.createElement(AddCalendarSource, {
```

With the above suggestion for imports.

2022-05-08 16:37 UTC, davish commented on src/settings.ts
> +								let sources = await new RemoteSource(
I think this would be better factored out as a static function on the `RemoteSource` class. Again, for readability, but also for ease of refactoring. The less logic in the view layer with react components, the better.

2022-05-08 16:37 UTC, davish commented on src/settings.ts
> +	async handleRemoval(
```suggestion
	async handleCalendarSourceRemoval(
```

Just to make the name more specific.

2022-05-08 16:37 UTC, davish commented on src/settings.ts
> +					// Only remove if the source is a saved source. That means
Maybe rephrasing this commend and putting it at the top of the function would be a good idea. It seems like it's the main reason that we need a special helper function rather than calling `Array.filter()` or something.

2022-05-08 16:37 UTC, davish commented on src/settings.ts
> +	async hide() {
What element is being hidden here?

2022-05-08 16:37 UTC, davish commented on src/types.ts
> +export type RRuleEventFrontmatter = {
Any reason why this isn't `&`-ed with `CommonEventFrontmatter`? Since all events have a title, at least.

2022-05-08 16:37 UTC, davish commented on src/types.ts
> +	ctag: string;
A comment on what a ctag is and how its used for cacheing would be useful here.

2023-03-03 15:02 UTC, divinites commented
Any update on this PR?

2023-03-18 15:17 UTC, davish commented
Hi @dojoteef, I hope you're doing well! The work to cache CalDAV calendars has been done as part of a larger rewrite of the plugin in #303, so I'm closing this PR. Thank you for your contributions!

2023-03-18 15:17 UTC, closed without merging